---
name: RPG-Item
version: 0.0.1
description: An extensible item system for RPGs
authors: [maceris]
main-class: com.ikalagaming.rpg.item.ItemPlugin
dependencies: [Random, Ikala-Attributes, Ikala-Database, EntityComponentSystem]
