name: TestComplexChainA
version: 0.0.1
main-class: com.ikalagaming.plugins.test.TestComplexChainA
authors: [maceris]
description: A plugin that has a complex dependency graph
dependencies: [TestComplexChainB]
soft-dependencies: [TestComplexChainC]
