//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2023.01.22 at 06:49:20 PM EST
//

package org.mapeditor.core;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Used to mark an object as an ellipse. The existing `x`, `y`,<br>
 * `width` and `height` attributes are used to determine the size<br>
 * of the ellipse.<br>
 * <br>
 *
 * @since 0.9
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ellipse")
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7",
	date = "2023-01-22T18:49:20-05:00")
public class Ellipse {

}
