//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2023.01.22 at 06:49:20 PM EST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mapeditor.org")
package org.mapeditor.core;
