---
name: RPG-Logic
version: 0.0.1-alpha
description: Handles RPG game logic
authors: [maceris]
main-class: com.ikalagaming.rpg.RPGPlugin
dependencies:
  - EntityComponentSystem
  - Ikala-Database
  - Ikala-Graphics
  - Ikala-Inventory
  - Ikala-World
  - Random