---
name: Ikala-Graphics
version: 0.0.2
description: A graphics plugin
authors: [maceris]
main-class: com.ikalagaming.graphics.GraphicsPlugin
dependencies: [Random]
libraries: [joml, lwjgl, lwjgl-glfw, lwjgl-shaderc, lwjgl-vma, lwjgl-vulkan, lwjgl-stb, lwjgl-freetype]
