name: TestComplexChainB
version: 0.0.1
main-class: com.ikalagaming.plugins.test.TestComplexChainB
authors: [maceris]
description: A plugin that has a complex dependency graph
soft-dependencies: [TestComplexChainD]
