---
name: RPG-GUI
version: 0.0.1
description: A GUI for the RPG
authors: [maceris]
main-class: com.ikalagaming.rpg.GUIPlugin
dependencies:
  - EntityComponentSystem
  - Ikala-Attributes
  - Ikala-Database
  - Ikala-Graphics
  - Ikala-Inventory
  - Ikala-Item
  - Random
