name: TestSoftDependCycleB
version: 0.0.1
description: The soft dependency for a plugin
authors: [maceris]
main-class: com.ikalagaming.plugins.test.TestSoftDependCycleB
soft-dependencies: [TestSoftDependCycleC]
