---
name: Factory-Client
version: 0.0.1-alpha
description: The client side of the factory plugin
authors: [maceris]
main-class: com.ikalagaming.factory.FactoryClientPlugin
dependencies:
  - Factory-Core
  - Ikala-Graphics
  - Random
# Only single player needs the server, so the client also runs without it, as in the asset editor
soft-dependencies:
  - Factory-Server
libraries: [joml]
