name: TestComplexChainC
version: 0.0.1
main-class: com.ikalagaming.plugins.test.TestComplexChainC
authors: [maceris]
description: A plugin that has a complex dependency graph
dependencies: [TestComplexChainA]
soft-dependencies: [TestComplexChainD]
