//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2023.01.22 at 06:49:20 PM EST
//

package org.mapeditor.core;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * This element is only used in case of isometric orientation, and<br>
 * determines how tile overlays for terrain and collision<br>
 * information are rendered.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grid")
@Generated(
        value = "com.sun.tools.xjc.Driver",
        comments = "JAXB RI v2.3.7",
        date = "2023-01-22T18:49:20-05:00")
public class Grid {

    /**
     * Orientation of the grid for the tiles in this tileset<br>
     * (orthogonal or isometric)
     */
    @XmlAttribute(name = "orientation")
    @Generated(
            value = "com.sun.tools.xjc.Driver",
            comments = "JAXB RI v2.3.7",
            date = "2023-01-22T18:49:20-05:00")
    protected Orientation orientation;

    /** Width of a grid cell */
    @XmlAttribute(name = "width")
    @Generated(
            value = "com.sun.tools.xjc.Driver",
            comments = "JAXB RI v2.3.7",
            date = "2023-01-22T18:49:20-05:00")
    protected Integer width;

    /** Height of a grid cell */
    @XmlAttribute(name = "height")
    @Generated(
            value = "com.sun.tools.xjc.Driver",
            comments = "JAXB RI v2.3.7",
            date = "2023-01-22T18:49:20-05:00")
    protected Integer height;

    /**
     * Height of a grid cell
     *
     * @return possible object is {@link Integer }
     */
    @Generated(
            value = "com.sun.tools.xjc.Driver",
            comments = "JAXB RI v2.3.7",
            date = "2023-01-22T18:49:20-05:00")
    public Integer getHeight() {
        return height;
    }

    /**
     * Orientation of the grid for the tiles in this tileset<br>
     * (orthogonal or isometric)
     *
     * @return possible object is {@link Orientation }
     */
    @Generated(
            value = "com.sun.tools.xjc.Driver",
            comments = "JAXB RI v2.3.7",
            date = "2023-01-22T18:49:20-05:00")
    public Orientation getOrientation() {
        return orientation;
    }

    /**
     * Width of a grid cell
     *
     * @return possible object is {@link Integer }
     */
    @Generated(
            value = "com.sun.tools.xjc.Driver",
            comments = "JAXB RI v2.3.7",
            date = "2023-01-22T18:49:20-05:00")
    public Integer getWidth() {
        return width;
    }

    /**
     * Height of a grid cell
     *
     * @param value allowed object is {@link Integer }
     */
    @Generated(
            value = "com.sun.tools.xjc.Driver",
            comments = "JAXB RI v2.3.7",
            date = "2023-01-22T18:49:20-05:00")
    public void setHeight(Integer value) {
        height = value;
    }

    /**
     * Orientation of the grid for the tiles in this tileset<br>
     * (orthogonal or isometric)
     *
     * @param value allowed object is {@link Orientation }
     */
    @Generated(
            value = "com.sun.tools.xjc.Driver",
            comments = "JAXB RI v2.3.7",
            date = "2023-01-22T18:49:20-05:00")
    public void setOrientation(Orientation value) {
        orientation = value;
    }

    /**
     * Width of a grid cell
     *
     * @param value allowed object is {@link Integer }
     */
    @Generated(
            value = "com.sun.tools.xjc.Driver",
            comments = "JAXB RI v2.3.7",
            date = "2023-01-22T18:49:20-05:00")
    public void setWidth(Integer value) {
        width = value;
    }
}
