//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2023.01.22 at 06:49:20 PM EST
//

package org.mapeditor.core;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * The template root element contains the saved map object and a<br>
 * tileset element that points to an external tileset, if the<br>
 * object is a tile object.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Template", propOrder = {"tileset", "object"})
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7",
	date = "2023-01-22T18:49:20-05:00")
public class Template {

	/**
	 * 
	 */
	@XmlElement(required = true, type = TileSet.class)
	@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7",
		date = "2023-01-22T18:49:20-05:00")
	protected TileSet tileset;
	/**
	 * 
	 */
	@XmlElement(required = true, type = MapObject.class)
	@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7",
		date = "2023-01-22T18:49:20-05:00")
	protected MapObject object;

	/**
	 * 
	 * @return possible object is {@link MapObjectData }
	 * 
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7",
		date = "2023-01-22T18:49:20-05:00")
	public MapObjectData getObject() {
		return this.object;
	}

	/**
	 * 
	 * @return possible object is {@link TileSetData }
	 * 
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7",
		date = "2023-01-22T18:49:20-05:00")
	public TileSetData getTileset() {
		return this.tileset;
	}

	/**
	 * 
	 * @param value allowed object is {@link MapObjectData }
	 * 
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7",
		date = "2023-01-22T18:49:20-05:00")
	public void setObject(MapObjectData value) {
		this.object = ((MapObject) value);
	}

	/**
	 * 
	 * @param value allowed object is {@link TileSetData }
	 * 
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7",
		date = "2023-01-22T18:49:20-05:00")
	public void setTileset(TileSetData value) {
		this.tileset = ((TileSet) value);
	}

}
